// data

// containers
// containers: application
export const CONTAINER_APPLICATION_ENABLE_BUSY_FLAG: string = 'CONTAINER_APPLICATION_ENABLE_BUSY_FLAG';
export const CONTAINER_APPLICATION_DISABLE_BUSY_FLAG: string = 'CONTAINER_APPLICATION_DISABLE_BUSY_FLAG';
